spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: wangyunliang
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-service:
      path: /auth/**
      serviceId: pig-auth-service
      stripPrefix: true
      sensitiveHeaders:
    pig-admin-service:
      path: /admin/**
      serviceId: pig-admin-service
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    key-prefix: pig-ratelimite 
    enabled: true 
    repository: REDIS 
    behind-proxy: true
    policies:
      pig-admin-service:
        limit: 100
        quota: 1
        refresh-interval: 3
  
security:
  sessions: stateless
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://pig-auth-service/user
      prefer-token-info: false
      service-id: pig-gateway
      
server:
  port: 9999
logging:
  config: classpath:logback.xml
