spring:
  redis:
    host: 123.206.94.20
    port: 6379
    password: redis
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  rabbitmq:
    host: 123.206.94.20
    port: 5672
    username: lengleng
    password: lengleng
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    auth-service:
      path: /auth/**
      serviceId: pig-auth-service
      stripPrefix: true
      sensitiveHeaders:
    pig-admin-service:
      path: /admin/**
      serviceId: pig-admin-service
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    key-prefix: pig-ratelimite 
    enabled: true 
    repository: REDIS 
    behind-proxy: true
    policies:
      pig-admin-service:
        limit: 100
        quota: 1
        refresh-interval: 3
  
security:
  sessions: stateless
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://pig-auth-service/user
      prefer-token-info: false
      service-id: pig-gateway
filter:
  urls:
    anon:
      - /auth/**
      - /auth/**
      
server:
  port: 9999
  
logging:
  config: classpath:logback.xml
