server:
  port: 4000
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
  redis:
    host: 123.206.94.20
    port: 6379
    password: redis
  rabbitmq:
    host: 123.206.94.20   
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.github.pig.admin.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    
logging:
  config: classpath:logback.xml

